### ISSUE TITLE
Specify network to scan

### ISSUE THREAD

**Issue by superswan** [SecurityWeekly/netslackbot#6]
```
def get_ip_address():
    s = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
    s.connect(("8.8.8.8", 80))
    return s.getsockname()[0]
```
Gets IP address based on default route. In my case it is selecting my VPN network. There is no way to specify a different network which may be necessary for some users. 

Suggesting an optional argument that allows a user to specify a network defaulting to `get_ip_address()` if no argument is given.

**Comment by pasadoorian** [comment]
Implemented in latest version.
